package com.udea.sagoa.dominio.user.model;


public enum Permission {
    ADMIN_READ,
    ADMIN_WRITE,
    ADMIN_DELETE,
    ADMIN_UPDATE,

    METER_READER_READ,
    METER_READER_WRITE,
    METER_READER_UPDATE,

    BILLING_CLERK_READ,
    BILLING_CLERK_WRITE,
    BILLING_CLERK_UPDATE,

    BILLING_ADMIN_READ,
    BILLING_ADMIN_WRITE,
    BILLING_ADMIN_UPDATE,

    CUSTOMER_SUPPORT_READ,
    CUSTOMER_SUPPORT_WRITE,
    CUSTOMER_SUPPORT_UPDATE,

    CUSTOMER_READ,
    CUSTOMER_WRITE,
    CUSTOMER_UPDATE,

    MAINTENANCE_OPERATOR_READ,
    MAINTENANCE_OPERATOR_WRITE,
    MAINTENANCE_OPERATOR_UPDATE,
}